### Consumindo API

In [1]:
import pandas as pd
## pandas readcsv
df = pd.read_csv('netflix_titles.csv')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [11]:
# Filter rows where 'Action' is in the 'listed_in' column
action_movies = df[df['listed_in'].str.contains('dsaddasdsadasd', case=False)]
if action_movies.empty:
    print("sem resultados")
else: 
    print('achou')

sem resultados

In [14]:
# Filter rows where 'Action' is in the 'listed_in' column
action_movies = df[df['title'].str.contains('Dick Johnson Is Dead', case=False)]
if action_movies.empty:
    print("sem resultados")
else: 
    print('achou title')

achou title

In [23]:
df['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [22]:
# search movies that release_year is between 2020 and 2022

json = {
    "start": "2020",
    "end": "2023",
    "method": "between",
    "date": "2021"
}


# between
# equalBigger
# equalLess
# equal
df[(df['release_year'] >= 2020) & (df['release_year'] <= 2021)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave GarcÃ­a, Pablo AzorÃ­n Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
32,s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...
34,s35,TV Show,Tayo and Little Wizards,NaN,"Dami Lee, Jason Lee, Bommie Catherine Han, Jen...",NaN,"September 17, 2021",2020,TV-Y7,1 Season,Kids' TV,Tayo speeds into an adventure when his friends...
...,...,...,...,...,...,...,...,...,...,...,...,...
5972,s5973,Movie,#cats_the_mewvie,Michael Margolis,NaN,Canada,"February 5, 2020",2020,TV-14,90 min,"Documentaries, International Movies",This pawesome documentary explores how our fel...
7594,s7595,Movie,Norm of the North: Family Vacation,Anthony Bell,"Andrew Toth, Lisa Durupt, Jonathan Holmes, Pau...",United States,"May 25, 2020",2020,TV-Y7,89 min,Children & Family Movies,"Stressed by his duties as king and father, Nor..."
8099,s8100,Movie,Straight Up,James Sweeney,"James Sweeney, Katie Findlay, Randall Park, Hi...",United States,"June 26, 2020",2020,TV-MA,96 min,"Comedies, Independent Movies, LGBTQ Movies",When a gay brainiac with OCD questions his ide...
8125,s8126,TV Show,Super Wings,NaN,"Luca Padovan, Evan Smolin, Junah Jang, Colin C...","United States, South Korea, China","December 1, 2020",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows",A cheerful jet and his transforming pals striv...
8132,s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,NaN,R. Kelly,United States,"April 13, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",As more women come forward with harrowing accu...

In [26]:
id = "s" + str(int(df['show_id'].max().split('s')[1]) + 1)
id

's1000'

In [43]:
df['show_id'].tail(1).to_string().split('s')[1]

'8807'

In [47]:
id = 's' + str(int(df['show_id'].tail(1).to_string().split('s')[1]) + 1)
id

's8808'

In [48]:
data = {
    "type" : "TV Show",
    "title" : "meu_filme",	
    "director" : "leo e vitor",
    "cast" : "leo e vitor",
    "country"	: "brazil",
    "date_added" : "2023",
    "release_year" : "2023",
    "rating" : "10",
    "duration" : "200",
    "listed_in" : "action, sci-fi",
    "description" : "movie about our college work"
}
id = 's' + str(int(df['show_id'].tail(1).to_string().split('s')[1]) + 1)

newMovie = {'show_id': id, 'type': data['type'], 'title': data['title'], 'director': data['director'], 'cast': data['cast'], 'country': data['country'], 'date_added': data['date_added'], 'release_year': data['release_year'], 'rating': data['rating'], 'duration': data['duration'], 'listed_in': data['listed_in'], 'description': data['description']}
df = df.append(newMovie, ignore_index=True)
df.tail(1)

C:\Users\garcez\AppData\Local\Temp\ipykernel_23404\2035201331.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(newMovie, ignore_index=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8807,s8808,TV Show,meu_filme,leo e vitor,leo e vitor,brazil,2023,2023,10,200,"action, sci-fi",movie about our college work

In [51]:
id = "s8808"
updated_data = {
    "type" : "TV Show",
    "title" : "novo filme",	
    "director" : "leo e vitor",
    "cast" : "leo e vitor",
    "country"	: "brazil",
    "date_added" : "2023",
    "release_year" : "2023",
    "rating" : "10",
    "duration" : "200",
    "listed_in" : "action, sci-fi",
    "description" : "movie about our college work"
}

df.loc[df['show_id'] == id, updated_data.keys()] = updated_data.values()

df.tail(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8807,s8808,TV Show,novo filme,leo e vitor,leo e vitor,brazil,2023,2023,10,200,"action, sci-fi",movie about our college work
8808,s8809,TV Show,novo filme,leo e vitor,leo e vitor,brazil,2023,2023,10,200,"action, sci-fi",movie about our college work

In [ ]:
from Movie import MovieSchema

movie_data = {
    "type" : "TV Show",
    "title" : "teeeeest",	
    "director" : "leo e vitor",
    "cast" : "leo e vitor",
    "country"	: "brazil",
    "date_added" : "2023",
    "release_year" : "2023",
    "rating" : "10",
    "duration" : "200",
    "listed_in" : "action, sci-fi",
    "description" : "movie about our college work"
}


movie_schema = MovieSchema()
validated_movie = movie_schema.load(movie_data)
id = 's' + str(int(df['show_id'].tail(1).to_string().split('s')[1]) + 1)
validated_movie['show_id'] = id

df.append(validated_movie, ignore_index=True).tail(2)

In [53]:
id = "s8808"
print(df.loc[df['show_id'] == id])

     show_id     type       title     director         cast country  \
8807   s8808  TV Show  novo filme  leo e vitor  leo e vitor  brazil

     date_added release_year rating duration       listed_in  \
8807       2023         2023     10      200  action, sci-fi

                       description
8807  movie about our college work

In [49]:
data = {
    "type" : "TV Show",
    "title" : "meu_filme",	
    "director" : "leo e vitor",
    "cast" : "leo e vitor",
    "country"	: "brazil",
    "date_added" : "2023",
    "release_year" : "2023",
    "rating" : "10",
    "duration" : "200",
    "listed_in" : "action, sci-fi",
    "description" : "movie about our college work"
}
id = 's' + str(int(df['show_id'].tail(1).to_string().split('s')[1]) + 1)

newMovie = {'show_id': id, 'type': data['type'], 'title': data['title'], 'director': data['director'], 'cast': data['cast'], 'country': data['country'], 'date_added': data['date_added'], 'release_year': data['release_year'], 'rating': data['rating'], 'duration': data['duration'], 'listed_in': data['listed_in'], 'description': data['description']}
df = df.append(newMovie, ignore_index=True)
df.tail(1)

C:\Users\garcez\AppData\Local\Temp\ipykernel_23404\2035201331.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(newMovie, ignore_index=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8808,s8809,TV Show,meu_filme,leo e vitor,leo e vitor,brazil,2023,2023,10,200,"action, sci-fi",movie about our college work